// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCCku3aQPWqm1JCc-i6FgaDwl7xpawxgY',
    appId: '1:1026403415219:web:af88c11b739909c270acc6',
    messagingSenderId: '1026403415219',
    projectId: 'cineverse-25579',
    authDomain: 'cineverse-25579.firebaseapp.com',
    storageBucket: 'cineverse-25579.firebasestorage.app',
    measurementId: 'G-BB2GQFMZQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0U8FOBh8qmwqhtmVuM9YJ-6zB-B0KyFM',
    appId: '1:1026403415219:android:186835d6c02fd78c70acc6',
    messagingSenderId: '1026403415219',
    projectId: 'cineverse-25579',
    storageBucket: 'cineverse-25579.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8zcFhDnrn7wYJc0xhvGBzoT3X812kTOw',
    appId: '1:1026403415219:ios:62385eae4b90dbbd70acc6',
    messagingSenderId: '1026403415219',
    projectId: 'cineverse-25579',
    storageBucket: 'cineverse-25579.firebasestorage.app',
    iosBundleId: 'com.example.cineverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8zcFhDnrn7wYJc0xhvGBzoT3X812kTOw',
    appId: '1:1026403415219:ios:62385eae4b90dbbd70acc6',
    messagingSenderId: '1026403415219',
    projectId: 'cineverse-25579',
    storageBucket: 'cineverse-25579.firebasestorage.app',
    iosBundleId: 'com.example.cineverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCCku3aQPWqm1JCc-i6FgaDwl7xpawxgY',
    appId: '1:1026403415219:web:dcd02fb0a418da7670acc6',
    messagingSenderId: '1026403415219',
    projectId: 'cineverse-25579',
    authDomain: 'cineverse-25579.firebaseapp.com',
    storageBucket: 'cineverse-25579.firebasestorage.app',
    measurementId: 'G-CQ20DHDM2V',
  );
}
